# Generated by Django 3.0.7 on 2020-06-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0002_auto_20200618_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.SlugField(default=1, max_length=160, unique=True),
            preserve_default=False,
        ),
    ]
