# Generated by Django 3.0.7 on 2020-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0004_auto_20200619_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
