# Generated by Django 3.0.7 on 2020-07-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0006_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
