# Generated by Django 3.0.7 on 2020-09-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0008_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={},
        ),
    ]
