# Generated by Django 3.0.7 on 2020-09-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0009_auto_20200919_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='story',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
    ]
