# Generated by Django 3.0.7 on 2020-09-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0010_auto_20200919_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='star',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='story',
        ),
        migrations.RemoveField(
            model_name='ratingstar',
            name='value',
        ),
    ]
