# Generated by Django 3.0.7 on 2020-09-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0011_auto_20200919_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
