# Generated by Django 3.1.2 on 2020-10-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0002_story_likes'),
        ('shortstoryapp', '0012_auto_20200919_2130'),
    ]

    operations = [
    ]
