# Generated by Django 3.1.2 on 2020-10-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0013_merge_20201011_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='likes',
        ),
    ]
