# Generated by Django 3.1.2 on 2020-10-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0017_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
