# Generated by Django 3.1.2 on 2020-10-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0022_likebutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
