# Generated by Django 3.1.2 on 2020-10-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortstoryapp', '0024_story_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='likes',
        ),
    ]
