# Generated by Django 3.1.2 on 2020-10-27 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortstoryapp', '0025_remove_story_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(related_name='story_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
